### ISSUE TITLE
Util file generated by node-sass isn't immediately picked up

### ISSUE THREAD

**Issue by mikemunsie** [mikemunsie/ember-export-sass-variables#1]
Found an issue where the first time you build the app, the util file isn't immediately recognized. Looking into a way for the util file generated to be immediately recognized in the tree.

Current workaround for tests (making your tests pass again):
```
ember build
ember test
```

For local development:
```
ember serve
// Save a scss file to trigger new util file
```

**Comment by mikemunsie** [comment]
Couldn't figure out the solution to this. Tis a tough bug, but now it's time to rest.

**Comment by minusfive** [comment]
@mikemunsie I didn't solve it, but implemented a workaround:

- https://github.com/minusfive/ember-cli-sass-variables-export/blob/master/package.json#L37-L38
- https://github.com/minusfive/ember-cli-sass-variables-export/blob/master/.travis.yml#L52-L57
- https://github.com/minusfive/ember-cli-sass-variables-export#running-tests
