### ISSUE TITLE
Forked, but happy to work on this if you prefer

### ISSUE THREAD

**Issue by minusfive** [mikemunsie/ember-export-sass-variables#2]
Howdy!

So I was looking to solve the same problem and looked for various solutions, but yours really seemed like the best one to me. I was sad to see it's no longer maintained as I found a couple of bugs and had some ideas on how to clean-up some things.

I needed it for a couple of projects I'm working on, though, so I went ahead and forked it, made the changes I needed and re-released it as [`ember-cli-sass-variables-export`](https://github.com/minusfive/ember-cli-sass-variables-export). Hope that's OK with you?

I dropped you an email earlier, but I'm sure you're busy. Someone on the Ember Slack suggested I reach out to you through here as well, just in case you'd rather I merge my work into this repo and take over maintenance.

Best regards, and thanks for putting all the original pieces together.

**Comment by mikemunsie** [comment]
Hello! 👋 

Sure thing, I'm completely cool with this and I've even updated this project's readme to point to your project. I'm no longer active with the Ember community, so I'm happy to help and transfer this project over. Definitely make it your own and I'm glad that this project has helped you out!

Cheers!

**Comment by minusfive** [comment]
That's awesome, thanks @mikemunsie!

**Comment by mikemunsie** [comment]
No probs! Thanks for taking this project over!!
